[package]
name = "cui_command"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base1112031 = { path = "../base1112031" }
mimalloc = { version = "0.1", default-features = false }
num-bigint = "0.4"
